### ISSUE TITLE
Input size to the first Conv2D layer

### ISSUE THREAD

**Issue by Lingaselvan** [ankur219/ECG-arrhythmia-classification-using-a-2-D-convolutional-neural-network.#2]
In your model.py file, you have mentioned the input size as below:
input_shape = IMAGE_SIZE + [3]

I believe we have a image size of 128*128*1 and therefore I understood the input shape should have been IMAGE_SIZE + [1]. Please correct me if I'm wrong.

**Comment by ankur219** [comment]
I saved the grayscale files using OpenCV. When I loaded them using OpenCV and checked their shape I got a tuple (128, 128, 3). So even though I have saved it as a grayscale image still it is showing three channels. Hence I had to add [3] and not [1].
